!python run_classifier.py \
  --task_name=NER \
  --do_train=true \
  --do_eval=true \
  --data_dir=data \
  --vocab_file=vocab.txt \
  --bert_config_file=bert_config.json \
  --init_checkpoint=bert_model.ckpt \ 
  --train_batch_size=32 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  --max_seq_length=128 \
  --output_dir=output \